server:
  port: 8080
  servlet:
    context-path: /

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
    password: password

spring:
  datasource:
    # driver-class-name: org.mariadb.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

    # url: jdbc:mariadb://14.49.44.142:3308/bi_solution?characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      # jdbc-url: jdbc:log4jdbc:mysql://14.49.44.142:3308/bi_solution?characterEncoding=UTF-8&serverTimezone=UTC
      jdbc-url: jdbc:log4jdbc:mysql://3.35.156.44:3306/bi_solution?characterEncoding=UTF-8&serverTimezone=UTC
      username: tera_bi
      password: ENC(+snoIMv61JsMV1LZyRm4YLmumnqlHEji)

  devtools:
    livereload:
      enabled: true

  #  thymeleaf:
#    prefix: classpath:templates/
#    suffix: .html
#    cache: "false"

  freemarker:
    # freemarker 템플릿 경로 지정
    template-loader-path: classpath:/templates
    # return 호출시 앞쪽에 자동으로 붙는 내용 정의
    # prefix:
    # return 호출시 뒷쪽에 자동으로 붙는 내용 정의
    suffix: .ftl
    # freemarker content type 정의
    contentType: text/html
    # freemarker charset 정의
    charset: UTF-8
    # 기본은 true (false 설정 하는 경우 프리마커 변경 내용이 바로 적용 됨)
    cache: false

mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
  # configuration:
  #   map-underscore-to-camel-case: "true"