spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://14.49.44.142:3308/bi_solution?characterEncoding=UTF-8&serverTimezone=UTC
    username: tera_bi
    password: tera202206

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: "false"

mybatis:
  mapper-locations: classpath:mappers/*.xml
  #   config-location: classpath:mybatis-config.xml

  configuration:
    map-underscore-to-camel-case: "true"

logging:
  level:
    com:
      prototype:
        domain:
          repository: TRACE
