server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    # url: jdbc:mariadb://localhost:3308/bi_solution?characterEncoding=UTF-8&serverTimezone=UTC
    bi:
      jdbc-url: ENC(Lf83qG39GDPua7RhuMWHNFuHkkpNVs/euV3PayRcvBYK20znWGJLZlHEh7q1r9o72Azrqywde7H16uoZCUlCSYCTY0VQ2nInDm1Uct6c5ABf6Q5sDyX3n6CVRTKC+vUb)
      username: ENC(XZPgJxY36iY857nLYH66bQ==)
      password: ENC(LovkE7rMb7CjfIwu/YbV57fA3r810HIP)
    groupware:
      jdbc-url: ENC(CyQEs0yQelDQIGKJiUdgaCow4FtIa+oIsfVQgQRp324vAyCQS2P3D/pYAj8Ntn+84uBra1yXAy81AkWULzk7x/XAP9WawySjcgFbRrGIklj1ojWXJlT1mQB39If20mDtM9K9VrdYtlSoWtKU7vFVow==)
      username: ENC(bedAHJCwifx+u+Qjb8LukgUaI3ud9s1R)
      password: ENC(v6aRD/xW1dGLYkHadbJXUCIu+aEvqRGsTolKeCVvEuU=)
      connection-test-query: SELECT 1

open-api:
  kosis-key: ENC(0BJV6leG2vBkRHeT3cjxi/H0i4hTSr3Xn46FHHi3vwLWe3geKqj8QRLV6IQhKEp9ffm2C8EGMqk=)
  ecos-key: ENC(c/He8UeNBODLuOqCvOi1Gwla3al1Cuc0bRk3dSNKrhE=)
  enara-key: ENC(SNQoha/X8+2pkeb22fHWpVmwhVcfoH1pZDckmm2Y6Fs=)
  enara-id: ENC(nrNwP4o7Aau+1li/O9BBYkgjz2vr060k)