server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    # url: jdbc:mariadb://localhost:3308/bi_solution?characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      jdbc-url: ENC(Lf83qG39GDPua7RhuMWHNFuHkkpNVs/euV3PayRcvBYK20znWGJLZlHEh7q1r9o72Azrqywde7H16uoZCUlCSYCTY0VQ2nInDm1Uct6c5ABf6Q5sDyX3n6CVRTKC+vUb)
      username: ENC(XZPgJxY36iY857nLYH66bQ==)
      password: ENC(LovkE7rMb7CjfIwu/YbV57fA3r810HIP)

open-api:
  kosis-key: ENC(TNkNVnrwQfccqMRbJQgYsW+iw+9MpSxP36QdHOuYREt6viqi5egecAU9sAlYJDVoZuvuLr9w+EY=)
  enara-key: ENC(SNQoha/X8+2pkeb22fHWpVmwhVcfoH1pZDckmm2Y6Fs=)
  enara-id: ENC(nrNwP4o7Aau+1li/O9BBYkgjz2vr060k)